version: '3.8'

services:
  movie_web:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: movie_web
    image: movie_web:0.2
    command: bash -c "bundle exec rake db:create && bundle exec rake db:migrate && ./bin/rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    networks:
      - movie_network
    volumes:
      - ./app:/rails

  vue-app:
    build:
      context: ./movie-review-app
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    environment:
      - VUE_APP_API_URL=http://movie_web:3000
    networks:
      - movie_network

networks:
  movie_network:
    external: true
