version: '3.8'

services:
  # Database service
  movie_db:
    image: postgres:latest
    container_name: movie_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - movie_network
    volumes:
      - pgadmin_data:/var/lib/postgresql/data

  # pgAdmin service for database management
  movie_pgadmin:
    image: dpage/pgadmin4
    container_name: movie_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - movie_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - movie_network

  # Rails backend service
  movie_web:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: movie_web
    image: movie_web:0.2
    command: bash -c "bundle exec rake db:create && bundle exec rake db:migrate && ./bin/rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    networks:
      - movie_network
    volumes:
      - ./app:/rails
    depends_on:
      - movie_db

  # Vue.js frontend service
  vue_app:
    build:
      context: ./movie-review-app
      dockerfile: Dockerfile
    container_name: vue_app
    ports:
      - "8082:80"
    networks:
      - movie_network
    environment:
      - VUE_APP_API_URL=http://movie_web:3000

volumes:
  pgadmin_data:

networks:
  movie_network:
    external: true
